export const EXERCISE_ALTERNATIVES: Record<string, string[]> = {
  "Bench Press":        ["DB Bench Press", "Machine Chest Press", "Incline DB Press"],
  "Incline DB Press":   ["Bench Press", "Machine Chest Press", "DB Bench Press"],
  "Shoulder Press":     ["DB Shoulder Press", "Arnold Press", "Machine Shoulder Press"],
  "Tricep Pushdown":    ["Overhead Tricep Extension", "Skull Crushers", "Dips"],
  "Lateral Raise":      ["Machine Lateral Raise", "Cable Lateral Raise"],
  "Lat Pulldown":       ["Pull-Ups", "Assisted Pull-Ups", "Seated Row"],
  "Seated Row":         ["Lat Pulldown", "Cable Row", "Single Arm DB Row"],
  "Face Pull":          ["Rear Delt Fly", "Cable Rear Delt Row"],
  "Bicep Curl":         ["Hammer Curl", "Preacher Curl", "Cable Curl"],
  "Squat":              ["Leg Press", "Goblet Squat", "Bulgarian Split Squat"],
  "Leg Press":          ["Squat", "Hack Squat", "Goblet Squat"],
  "Romanian Deadlift":  ["Stiff Leg Deadlift", "Hamstring Curl", "Hip Thrust"],
  "Leg Extension":      ["Sissy Squat", "Spanish Squat"],
  "Hamstring Curl":     ["Romanian Deadlift", "Nordic Curl"],
  "Calf Raise":         ["Seated Calf Raise", "Single Leg Calf Raise"],
  "Hip Thrust":         ["Romanian Deadlift", "Glute Bridge"],
  "Plank":              ["Dead Bug", "Ab Wheel"],
};
